CREATE DATABASE SITEMA;

CREATE TABLE USUARIO(
ID INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(100) NOT NULL,
LOGIN VARCHAR(100) NOT NULL,
SENHA VARCHAR(100) NOT NULL,
NIVEL VARCHAR(100) NOT NULL,
IDSUPERIOR INT NOT NULL,
SITUACAO INT NOT NULL,
PRIMARY KEY(ID));

INSET INTO USUARIO(NOME,LOGIN,SENHA,NIVEL,IDSUPERIOR,BLOQUEADO)
VALUES ('ADIMIN','ADIMIN',SHA('123'),1,0,1);