CREATE DATABASE CORE68;


CREATE TABLE USUARIO(
	ID INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	LOGIN VARCHAR(100) NOT NULL,
	SENHA VARCHAR(100) NOT NULL,
	NIVEL VARCHAR(100) NOT NULL,
	IDSUPERIOR INT NOT NULL,
	SITUACAO INT NOT NULL,
	PRIMARY KEY(ID));


CREATE TABLE UNIDADE(
	ID INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(50) NOT NULL,
	DATA VARCHAR(10) NOT NULL,
	IDUSUARIO INT NOT NULL,
	SIGLA VARCHAR(10) NOT NULL,
	ENDERECO VARCHAR(250) NOT NULL,
	SITUACAO INT NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(ID));

CREATE TABLE AMBIENTE(
	ID INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	DATA VARCHAR(10) NOT NULL,
	IDUSUARIO INT NOT NULL,
	IDUNIDADE INT NOT NULL,
	DESCRICAO VARCHAR(250) NOT NULL,
	SITUACAO INT NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(ID),
	FOREIGN KEY (IDUNIDADE) REFERENCES UNIDADE(ID));
	
	
CREATE TABLE CARGO(
	ID INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	IDUSUARIO INT NOT NULL,
	SITUACAO INT NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(ID));


CREATE TABLE FUNCIONARIO(
	ID INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(150) NOT NULL,
	IDCARGO INT NOT NULL,
	TURNO INT NOT NULL,
	SUPERIOR INT NOT NULL,
	IDUNIDADE INT NOT NULL,
	IDUSUARIO INT NOT NULL,
	DATA VARCHAR(10) NOT NULL,
	SITUACAO INT NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY (IDCARGO) REFERENCES CARGO (ID),
	FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(ID),
	FOREIGN KEY (IDUNIDADE) REFERENCES UNIDADE (ID));

CREATE TABLE GRUPO(
	ID INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	IDUSUARIO INT NOT NULL,
	SITUACAO INT NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(ID));


CREATE TABLE SUBGRUPO(
	ID INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	IDGRUPO INT NOT NULL,
	IDUSUARIO INT NOT NULL,
	SITUACAO INT NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(ID),
	FOREIGN KEY (IDGRUPO) REFERENCES GRUPO (ID));
	

CREATE TABLE ATIVO(
	ID INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	IDSUBGRUPO  INT NOT NULL,
	IDAMBIENTE  INT NOT NULL,
	IDSTATUS VARCHAR(15) NOT NULL,
	IDUSUARIO INT NOT NULL,
	CODIGOBARRA VARCHAR(30) NOT NULL,
	DATACAD VARCHAR(10) NOT NULL,
	DESCRICAO VARCHAR(250) NOT NULL,
	SITUACAO INT NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY (IDSUBGRUPO) REFERENCES SUBGRUPO (ID),
	FOREIGN KEY (IDAMBIENTE) REFERENCES AMBIENTE (ID),
	FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(ID));

CREATE TABLE MOVIMENTACAO(
	ID INT NOT NULL AUTO_INCREMENT,
	MOTIVO VARCHAR(250) NOT NULL,
	IDSTATUS VARCHAR(15) NOT NULL,
	IDAMBIENTEORIGEM INT NOT NULL,
	IDAMBIENTEDESTINO INT NOT NULL,
	IDATIVO INT NOT NULL,
	IDUSUARIO INT  NOT NULL,
	DATAENTRADA VARCHAR(10) NOT NULL,
	DATASAIDA VARCHAR(10) NOT NULL,
	DATACADMOV VARCHAR(10) NOT NULL,
	DESCRICAO TEXT(300) NOT NULL,
	SITUACAO INT NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY (IDATIVO) REFERENCES ATIVO (ID),
	FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(ID));




INSERT INTO USUARIO(NOME,LOGIN,SENHA,NIVEL,IDSUPERIOR,SITUACAO)
VALUES ('Administrador','nessa',SHA('123456'),1,1,0),
       ('Supervisor','luiz',SHA('123456'),2,1,0),
       ('Operador','tutu',SHA('123456'),3,2,0),
       ('Administrador','rute',SHA('123456'),1,1,1),
       ('Supervisor','judite',SHA('123456'),2,1,1),
       ('Operador','rob',SHA('123456'),3,2,1),
       ('Administrador','sant',SHA('123456'),1,1,0),
       ('Supervisor','eva',SHA('123456'),2,1,0),
       ('Operador','lala',SHA('123456'),3,2,0),
       ('Administrador','lula',SHA('123456'),1,1,1),
       ('Supervisor','xuda',SHA('123456'),2,1,1),
       ('Operador','xuxa',SHA('123456'),3,2,1),
       ('Administrador','xaxa',SHA('123456'),1,1,0),
       ('Supervisor','xaca',SHA('123456'),2,1,0),
       ('Operador','chuva',SHA('123456'),3,2,0),
       ('Administrador','xena',SHA('123456'),1,1,1),
       ('Supervisor','mist',SHA('123456'),2,1,1),
       ('Operador','taragah',SHA('123456'),3,2,1);



	
	
	
	
	
	
	
	
	
	
	
	
	

	
	
	
	
	
	

	